sudo: required

services:
  - docker
language: python
python:
  - "3.4"
script:
  - docker-compose up -d
  - docker exec -u root -ti shackbureau_web_1 py.test
notifications:
  irc:
    channels:
      - "irc.freenode.org##shackbureau"
    use_notice: true
